version: "3.9"

services:
  flask_app:
    build: .
    depends_on:
      - mongodb
      - redis
    tty: true
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: test
      HOST: host.docker.internal

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
