"""
The logs folder contains log files generated by the NotifyMe API.

This folder contains log files generated by the various loggers used in the NotifyMe API.
These log files can be used to diagnose issues with the API and monitor its performance.
"""
